---
version: '3.7'

services:
  app:
    container_name: app
    hostname: app
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:5000"
    networks:
      - local_network
    restart: unless-stopped

networks:
  local_network: {}
...